version: '2.1'

services:
  mongodb:
    container_name: mongodb_jvm_js
    hostname: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "test"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_storage:/var/lib/mongo
      - mongodb_log:/var/log/mongodb
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 64000
        hard: 64000
    mem_limit: 2000m
    memswap_limit: 2200m
    network_mode: "bridge"
    ports:
      - "27017:27017"

volumes:
  mongodb_storage:
  mongodb_log:
